version: "3"
services:
    redis:
        image: redis:alpine
        volumes:
            - redis-data:/data
        networks:
            - flow-network

    app:
        image: ghcr.io/cestef/uses.ink:latest
        ports:
            - "3000:3000"
        env_file:
            - .env.production
        depends_on:
            - redis
        networks:
            - flow-network

volumes:
    redis-data:

networks:
    flow-network:
        driver: bridge
