services:
    redis:
        image: redis:alpine
        volumes:
            - redis-data:/data
        networks:
            - base-network

    app:
        image: ghcr.io/cestef/uses.ink:latest
        ports:
            - "8765:8765"
        env_file:
            - .env
        depends_on:
            - redis
        networks:
            - base-network

volumes:
    redis-data:

networks:
    base-network:
        driver: bridge
