version: "3.8"
services:
    redis:
        image: redis:alpine
        volumes:
            - redis-data:/data
        networks:
            - base-network

    app:
        image: uses.ink
        ports:
            - "3000:3000"
        env_file:
            - .env
        depends_on:
            - redis
        networks:
            - base-network

volumes:
    redis-data:

networks:
    base-network:
        driver: bridge
